### ISSUE TITLE
Two errors on generate.ts

### ISSUE THREAD

**Issue by naomigrace** [OADA/jwt-bearer-client-auth#13]
<img width="834" alt="Screen Shot 2022-07-13 at 3 32 09 PM" src="https://user-images.githubusercontent.com/18753283/178816421-f1fd00f7-df45-4d86-bfd3-3c4120fb80c8.png">

Getting these two errors when trying to build a project that uses this library:

- Unused '@ts-expect-error' directive.
- Property 'kid' does not exist on type 'JWK'.
  Property 'kid' does not exist on type 'JWKpem'.

Please advise

**Comment by awlayton** [comment]
Your project should not be building this library. You should be using the built JavaScript from `dist/` not the TypeScript from `src/`.

This project still builds itself fine.
